//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;CycleHeads&quot;:[{&quot;X&quot;:36,&quot;Y&quot;:36},{&quot;X&quot;:2,&quot;Y&quot;:36},{&quot;X&quot;:2,&quot;Y&quot;:2},{&quot;X&quot;:36,&quot;Y&quot;:2}],&quot;RectangleWalls&quot;:[]}.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;CycleHeads&quot;:[{&quot;X&quot;:28,&quot;Y&quot;:28},{&quot;X&quot;:10,&quot;Y&quot;:28},{&quot;X&quot;:10,&quot;Y&quot;:10},{&quot;X&quot;:28,&quot;Y&quot;:10}],&quot;RectangleWalls&quot;:[{&quot;LeftTopPoint&quot;:{&quot;X&quot;:13,&quot;Y&quot;:13},&quot;Width&quot;:13,&quot;Height&quot;:13}]}.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;CycleHeads&quot;:[{&quot;X&quot;:19,&quot;Y&quot;:36},{&quot;X&quot;:2,&quot;Y&quot;:19},{&quot;X&quot;:19,&quot;Y&quot;:2},{&quot;X&quot;:36,&quot;Y&quot;:19}],&quot;RectangleWalls&quot;:[{&quot;LeftTopPoint&quot;:{&quot;X&quot;:26,&quot;Y&quot;:26},&quot;Width&quot;:13,&quot;Height&quot;:13},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:0,&quot;Y&quot;:26},&quot;Width&quot;:13,&quot;Height&quot;:13},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:0,&quot;Y&quot;:0},&quot;Width&quot;:13,&quot;Height&quot;:13},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:26,&quot;Y&quot;:0},&quot;Width&quot;:13,&quot;Height&quot;:13}]}.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;CycleHeads&quot;:[{&quot;X&quot;:30,&quot;Y&quot;:38},{&quot;X&quot;:8,&quot;Y&quot;:38},{&quot;X&quot;:8,&quot;Y&quot;:0},{&quot;X&quot;:30,&quot;Y&quot;:0}],&quot;RectangleWalls&quot;:[{&quot;LeftTopPoint&quot;:{&quot;X&quot;:0,&quot;Y&quot;:0},&quot;Width&quot;:8,&quot;Height&quot;:39},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:31,&quot;Y&quot;:0},&quot;Width&quot;:8,&quot;Height&quot;:39}]}.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;CycleHeads&quot;:[{&quot;X&quot;:36,&quot;Y&quot;:36},{&quot;X&quot;:2,&quot;Y&quot;:36},{&quot;X&quot;:2,&quot;Y&quot;:2},{&quot;X&quot;:36,&quot;Y&quot;:2}],&quot;RectangleWalls&quot;:[{&quot;LeftTopPoint&quot;:{&quot;X&quot;:5,&quot;Y&quot;:5},&quot;Width&quot;:8,&quot;Height&quot;:12},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:26,&quot;Y&quot;:22},&quot;Width&quot;:8,&quot;Height&quot;:12},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:18,&quot;Y&quot;:5},&quot;Width&quot;:16,&quot;Height&quot;:12},{&quot;LeftTopPoint&quot;:{&quot;X&quot;:5,&quot;Y&quot;:22},&quot;Width&quot;:16,&quot;Height&quot;:12}]}.
        /// </summary>
        internal static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вам предоставляется возможность прокатиться на мотоцикле из фильма tron. Все мотоциклы оставляют след. Пользователь соревнуется с вражескими мотоциклами, пытаясь заставить их разбиться об препятствия, стены арены или след от своего или других мотоциклов. Боты имеют по одной жизни в рамках уровня.
        ///Мотоцикл пользователя голубого цвета. Пользователь проигрывает, если его мотоцикл врезается в любой след, в том числе и свой, в чужой мотоцикл, в препятствие или стену.
        ///Цель игры - подрезать всех врагов и пройти  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TextInstruction {
            get {
                return ResourceManager.GetString("TextInstruction", resourceCulture);
            }
        }
    }
}
